apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webserver-deployment.yaml
  - webserver-service.yaml
images:
  - name: nginx
    newName: 813953403023.dkr.ecr.us-east-2.amazonaws.com/webserver # {"$imagepolicy": "flux-system:gitops-demo:name"}
    newTag: main-60c2e65-1625045330 # {"$imagepolicy": "flux-system:gitops-demo:tag"}
